-- Run this once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password_hash text not null,
  role text not null default 'user' check (role in ('user','admin')),
  email_verified boolean not null default false,
  admin_approved boolean not null default false,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  last_login_at timestamptz
);

create table if not exists public.email_otps (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  otp_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists email_otps_user_idx on public.email_otps(user_id);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  csrf_token text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists sessions_token_idx on public.sessions(token_hash);

create table if not exists public.topics (
  id text primary key,
  name text not null,
  section text not null check (section in ('verbal','numerical')),
  description text not null
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  topic_id text not null references public.topics(id) on delete cascade,
  question_index integer not null check (question_index between 0 and 9),
  prompt text not null,
  options_json jsonb not null,
  correct_index integer not null check (correct_index between 0 and 3),
  explanation text not null,
  unique(topic_id, question_index)
);

create table if not exists public.progress (
  user_id uuid not null references public.users(id) on delete cascade,
  topic_id text not null references public.topics(id) on delete cascade,
  completed_count integer not null default 0 check (completed_count between 0 and 10),
  updated_at timestamptz not null default now(),
  primary key(user_id, topic_id)
);

-- The browser never talks to Supabase directly. The Netlify Function uses the service role.
-- Keep RLS enabled with no public policies so anon users cannot read or write these tables.
alter table public.users enable row level security;
alter table public.email_otps enable row level security;
alter table public.sessions enable row level security;
alter table public.topics enable row level security;
alter table public.questions enable row level security;
alter table public.progress enable row level security;
