import express from 'express';
import serverless from 'serverless-http';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import nodemailer from 'nodemailer';
import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';

const app = express();
app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json({ limit: '20kb' }));
app.use(cookieParser());
const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const isProd = process.env.NODE_ENV === 'production';
const now = () => new Date().toISOString();
const sha = value => crypto.createHash('sha256').update(value).digest('hex');
const otpHash = value => crypto.createHmac('sha256', process.env.OTP_SECRET || 'dev-change-this').update(value).digest('hex');
const same = (a,b) => { const x=Buffer.from(a); const y=Buffer.from(b); return x.length===y.length && crypto.timingSafeEqual(x,y); };
function hashPassword(password){const salt=crypto.randomBytes(16);return `${salt.toString('hex')}:${crypto.scryptSync(password,salt,64).toString('hex')}`;}
function verifyPassword(password,stored){try{const [saltHex,hashHex]=stored.split(':');const out=crypto.scryptSync(password,Buffer.from(saltHex,'hex'),64);return same(out,Buffer.from(hashHex,'hex'));}catch{return false;}}
function publicUser(user){return {id:user.id,email:user.email,role:user.role,email_verified:!!user.email_verified,admin_approved:!!user.admin_approved};}
const safe = handler => (req,res,next) => Promise.resolve(handler(req,res,next)).catch(next);
const authLimiter = rateLimit({windowMs:15*60*1000,max:30,standardHeaders:true,legacyHeaders:false,message:{message:'Too many attempts. Try again later.'}});
app.use('/api/auth', authLimiter);
const smtp = process.env.SMTP_HOST ? nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}) : null;
async function sendOtp(email,otp){if(!smtp){console.log(`[DEV OTP] ${email}: ${otp}`);return;}await smtp.sendMail({from:process.env.MAIL_FROM,to:email,subject:'AFPSAT email verification code',text:`Your verification code is ${otp}. It expires in 10 minutes.`});}
async function findUserByEmail(email){const {data,error}=await db.from('users').select('*').eq('email',email).maybeSingle();if(error)throw error;return data;}
async function findSession(req){const raw=req.cookies.afpsat_session;if(!raw)return null;const {data:s,error}=await db.from('sessions').select('*').eq('token_hash',sha(raw)).maybeSingle();if(error||!s||new Date(s.expires_at).getTime()<Date.now())return null;const {data:user,error:userError}=await db.from('users').select('*').eq('id',s.user_id).maybeSingle();if(userError||!user)return null;return {session:s,user};}
const auth=safe(async(req,res,next)=>{const found=await findSession(req);if(!found)return res.status(401).json({message:'Login required'});req.session=found.session;req.user=found.user;next();});
function csrf(req,res,next){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();if(!req.session||req.get('x-csrf-token')!==req.session.csrf_token)return res.status(403).json({message:'Invalid CSRF token'});next();}
function approved(req,res,next){if(!req.user.email_verified)return res.status(403).json({code:'EMAIL_NOT_VERIFIED',message:'Verify your email first.'});if(!req.user.admin_approved)return res.status(403).json({code:'PENDING_APPROVAL',message:'Your email is verified, but an admin must approve your account.'});next();}
async function createSession(userId){const raw=crypto.randomBytes(32).toString('base64url'),csrf=crypto.randomBytes(24).toString('base64url'),days=Number(process.env.SESSION_DAYS||7);const {data,error}=await db.from('sessions').insert({user_id:userId,token_hash:sha(raw),csrf_token:csrf,expires_at:new Date(Date.now()+days*86400000).toISOString()}).select('*').single();if(error)throw error;return {raw,csrf,session:data};}
async function ensureAdmin(){const email=(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),password=process.env.ADMIN_PASSWORD||'';if(!email||!password)return;const user=await findUserByEmail(email);if(user){if(user.role!=='admin'||!user.admin_approved){await db.from('users').update({role:'admin',email_verified:true,admin_approved:true,approved_at:now()}).eq('id',user.id);}return;}await db.from('users').insert({email,password_hash:hashPassword(password),role:'admin',email_verified:true,admin_approved:true,approved_at:now()});}
app.get('/api/auth/me',safe(async(req,res)=>{const found=await findSession(req);res.json(found?{user:publicUser(found.user),csrf:found.session.csrf_token}:{user:null});}));
app.post('/api/auth/register',safe(async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||password.length<12)return res.status(400).json({message:'Use a valid email and a password of at least 12 characters.'});if(await findUserByEmail(email))return res.status(409).json({message:'Account already exists. Log in or verify the pending email.'});const {data:user,error}=await db.from('users').insert({email,password_hash:hashPassword(password)}).select('*').single();if(error)throw error;const otp=String(crypto.randomInt(100000,1000000));await db.from('email_otps').insert({user_id:user.id,otp_hash:otpHash(otp),expires_at:new Date(Date.now()+600000).toISOString()});try{await sendOtp(email,otp);}catch(error){await db.from('users').delete().eq('id',user.id);throw error;}res.status(201).json({requiresOtp:true,message:'Account created. Check your email for the OTP.'});}));
app.post('/api/auth/verify-email',safe(async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),otp=String(req.body.otp||'').trim(),user=await findUserByEmail(email);if(!user)return res.status(400).json({message:'Invalid or expired code.'});const {data:row}=await db.from('email_otps').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!row||new Date(row.expires_at).getTime()<Date.now()||row.attempts>=5)return res.status(400).json({message:'Invalid or expired code.'});if(!same(otpHash(otp),row.otp_hash)){await db.from('email_otps').update({attempts:row.attempts+1}).eq('id',row.id);return res.status(400).json({message:'Invalid or expired code.'});}await db.from('users').update({email_verified:true}).eq('id',user.id);await db.from('email_otps').delete().eq('user_id',user.id);res.json({message:'Email verified. Await admin approval.'});}));
app.post('/api/auth/login',safe(async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),user=await findUserByEmail(email);if(!user||!verifyPassword(password,user.password_hash))return res.status(401).json({message:'Invalid email or password.'});if(!user.email_verified)return res.status(403).json({code:'EMAIL_NOT_VERIFIED',message:'Verify your email before logging in.'});if(!user.admin_approved)return res.status(403).json({code:'PENDING_APPROVAL',message:'Email verified. An admin still needs to approve your account.'});const created=await createSession(user.id);await db.from('users').update({last_login_at:now()}).eq('id',user.id);res.cookie('afpsat_session',created.raw,{httpOnly:true,sameSite:'lax',secure:isProd,maxAge:Number(process.env.SESSION_DAYS||7)*86400000});res.json({user:publicUser(user),csrf:created.csrf});}));
app.post('/api/auth/logout',auth,csrf,safe(async(req,res)=>{await db.from('sessions').delete().eq('id',req.session.id);res.clearCookie('afpsat_session');res.json({ok:true});}));
app.get('/api/topics',auth,approved,safe(async(req,res)=>{const [{data:topics,error:topicsError},{data:progress,error:progressError}]=await Promise.all([db.from('topics').select('*').order('section').order('id'),db.from('progress').select('topic_id,completed_count').eq('user_id',req.user.id)]);if(topicsError||progressError)throw topicsError||progressError;const map=new Map(progress.map(p=>[p.topic_id,Math.round(p.completed_count/10*100)]));res.json({topics:topics.map(t=>({...t,completed_count:map.get(t.id)||0}))});}));
app.get('/api/topics/:id/questions',auth,approved,safe(async(req,res)=>{const [{data:topic},{data:questions,error}]=await Promise.all([db.from('topics').select('*').eq('id',req.params.id).maybeSingle(),db.from('questions').select('question_index,prompt,options_json').eq('topic_id',req.params.id).order('question_index')]);if(error)throw error;if(!topic)return res.status(404).json({message:'Topic not found'});res.json({topic,questions:questions.map(q=>({question_index:q.question_index,prompt:q.prompt,options:q.options_json}))});}));
app.post('/api/topics/:id/questions/:index/answer',auth,approved,csrf,safe(async(req,res)=>{const index=Number(req.params.index),choice=Number(req.body.choice);if(!Number.isInteger(index)||index<0||index>9||!Number.isInteger(choice)||choice<0||choice>3)return res.status(400).json({message:'Invalid answer.'});const {data:q,error}=await db.from('questions').select('*').eq('topic_id',req.params.id).eq('question_index',index).maybeSingle();if(error)throw error;if(!q)return res.status(404).json({message:'Question not found'});const correct=choice===q.correct_index;if(correct){const {data:old}=await db.from('progress').select('completed_count').eq('user_id',req.user.id).eq('topic_id',q.topic_id).maybeSingle();const next=Math.max(old?.completed_count||0,index+1);await db.from('progress').upsert({user_id:req.user.id,topic_id:q.topic_id,completed_count:Math.min(next,10),updated_at:now()},{onConflict:'user_id,topic_id'});}let next=null;if(correct&&index<9){const {data:n}=await db.from('questions').select('question_index,prompt,options_json').eq('topic_id',q.topic_id).eq('question_index',index+1).maybeSingle();if(n)next={question_index:n.question_index,prompt:n.prompt,options:n.options_json};}res.json({correct,correct_index:q.correct_index,explanation:q.explanation,next});}));
app.get('/api/admin/users',auth,approved,safe(async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({message:'Admin permission required.'});const {data,error}=await db.from('users').select('id,email,role,email_verified,admin_approved,created_at').order('created_at',{ascending:false});if(error)throw error;res.json({users:data});}));
app.post('/api/admin/users/:id/approve',auth,approved,csrf,safe(async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({message:'Admin permission required.'});const {error}=await db.from('users').update({admin_approved:true,approved_at:now()}).eq('id',req.params.id).eq('role','user');if(error)throw error;res.json({ok:true});}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Server error'});});
await ensureAdmin().catch(error=>console.error('Admin bootstrap failed:',error.message));
export const handler=serverless(app);
export default handler;
